# Generated by Django 4.0.2 on 2022-02-19 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LikeAPP', '0001_initial'),
        ('PostAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelpostlike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='PostAPP.modelpost', verbose_name='Gönderi'),
        ),
    ]
