# Generated by Django 4.0.2 on 2022-02-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modeluser',
            options={'verbose_name': 'Kullanıcı', 'verbose_name_plural': 'Kullanıcılar'},
        ),
        migrations.AddField(
            model_name='modeluser',
            name='biography',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Biyogrofi'),
        ),
        migrations.AlterField(
            model_name='modeluser',
            name='profilePhoto',
            field=models.ImageField(blank=True, null=True, upload_to='ProfilePhotos'),
        ),
    ]
