# Generated by Django 4.0.2 on 2022-02-25 10:57

import CommentAPP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Yorum İçeriği')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('unique_id', models.CharField(default=CommentAPP.models.createNewUniqueID, editable=False, max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Yorum',
                'verbose_name_plural': 'Yorumlar',
                'db_table': 'Comments',
            },
        ),
    ]
