# Generated by Django 4.0.2 on 2022-02-25 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PostAPP', '0001_initial'),
        ('CommentAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PostAPP.modelpost', verbose_name='Post'),
        ),
    ]
