# Generated by Django 4.0.2 on 2022-02-25 07:37

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('CommentAPP', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='modelcomment',
            managers=[
                ('actives', django.db.models.manager.Manager()),
            ],
        ),
    ]
