# Generated by Django 4.0.2 on 2022-02-19 10:33

import PostAPP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='İçerik')),
                ('image', models.ImageField(blank=True, null=True, upload_to='PostImages')),
                ('createdDate', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('unique_id', models.CharField(default=PostAPP.models.create_new_ref_number, editable=False, max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Gönderi',
                'verbose_name_plural': 'Gönderiler',
                'db_table': 'Posts',
            },
        ),
    ]
