# Generated by Django 4.0.2 on 2022-02-19 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostAPP', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelpost',
            old_name='unique_id',
            new_name='slug',
        ),
    ]
