# Generated by Django 4.0.2 on 2022-02-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostAPP', '0003_modelcategory_modelpost_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='PostImages'),
        ),
    ]
