# Generated by Django 4.0.2 on 2022-02-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostAPP', '0004_alter_modelpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpost',
            name='categories',
            field=models.ManyToManyField(related_name='posts', to='PostAPP.ModelCategory', verbose_name='Kategoriler'),
        ),
    ]
