# Generated by Django 4.0.2 on 2022-02-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelContanct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(help_text='Adınız', max_length=100, verbose_name='İsim')),
                ('lastName', models.CharField(help_text='Soy Adınız', max_length=100, verbose_name='Soy isim')),
                ('email', models.EmailField(help_text='Email Adresiniz', max_length=400, verbose_name='Email')),
                ('message', models.TextField(help_text='Mesajınız', max_length=500, verbose_name='Mesaj')),
            ],
        ),
    ]
